---
# tasks file for golem-docker

- name: Install docker-ce key
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
  become: yes

- name: Add docker repo, 64bit ONLY!
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb['codename'] }} stable"
  become: yes

- name: Install docker-ce
  apt:
    name: docker-ce
    state: latest
    update_cache: yes
  become: yes
  notify: restart docker

- name: create dataroot
  become: yes
  file:
    path: "{{ golem_docker_dataroot }}"
    state: directory

- name: create systemd config directory
  become: yes
  file:
    path: "/etc/systemd/system/docker.service.d"
    state: directory

- name: override docker config
  when: golem_docker_dataroot != "/var/lib/docker"
  block:
    - name: get ExecStart line
      command: grep ExecStart= /lib/systemd/system/docker.service
      changed_when: False
      register: golem_docker_exec_start

    - name: override docker config
      become: yes
      template:
        src: "override.conf.j2"
        dest: "/etc/systemd/system/docker.service.d/override.conf"
      notify: restart docker

- name: default docker config
  become: yes
  when: golem_docker_dataroot == "/var/lib/docker"
  file:
    path: "/etc/systemd/system/docker.service.d/override.conf"
    state: absent
  notify: restart docker

- name: start docker
  systemd:
    daemon_reload: yes
    name: docker
    state: started
    enabled: yes
  become: yes
